---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dyad-gateway
  namespace: dyad-gateway
  labels:
    app.kubernetes.io/name: dyad-gateway
    app.kubernetes.io/component: serviceaccount

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dyad-gateway-sandbox
  name: dyad-gateway-sandbox-manager
  labels:
    app.kubernetes.io/name: dyad-gateway
    app.kubernetes.io/component: rbac
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "get", "list", "watch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch", "delete"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dyad-gateway-sandbox-binding
  namespace: dyad-gateway-sandbox
  labels:
    app.kubernetes.io/name: dyad-gateway
    app.kubernetes.io/component: rbac
subjects:
- kind: ServiceAccount
  name: dyad-gateway
  namespace: dyad-gateway
roleRef:
  kind: Role
  name: dyad-gateway-sandbox-manager
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Namespace
metadata:
  name: dyad-gateway-sandbox
  labels:
    name: dyad-gateway-sandbox
    app.kubernetes.io/name: dyad-gateway
    app.kubernetes.io/component: sandbox